version: '3.4'

services:
  socdemostats:
    image: socdemostats
    build: ./app
    ports:
      - 8000:8000
    volumes:
      - ./app:/usr/src/app:delegated
    env_file:
      - ./app/.env

  db:
    container_name: postgres
    image: postgis/postgis
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=socdem
      - PGDATA=/data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db: